accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name="register"),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

# url patterns for learning log
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('accounts/', include('accounts.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics. E.g. /topics
    path('topics/', views.topic_list, name='topics'),
    # Detail page for a single topic. E.g. /topics/5
    path('topics/<int:topic_id>/', views.topic_detail, name='topic'),
    # Form page to add a new topic. E.g. /new_topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Form page for adding a new entry for a topic. E.g. /new_entry/2
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Form page to edit an existing entry. /edit_entry. E.g. /edit_entry/4
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry')
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representation of the entry."""
        entry = self.text[:50]
        if len(self.text) > 50:
            entry += "..."
        return entry

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=150, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(
            attrs={'cols': 80,
                   'class': 'form-control',
                   'id': 'entryTextInput',
                   'placeholder': 'entry text',
                   'style': 'height: 150px',
                   },
        )}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
# from django.contrib.auth.forms import UserCreationForm

from .forms import RegistrationForm


# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = RegistrationForm()
    else:
        # Process completed form.
        form = RegistrationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then direct to home page.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
""" learning_logs/views"""
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topic_list(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic_detail(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure that the topic is owned by the current user
    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted; create a blank form. If method is not 'POST' it will be GET by default.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)

        if form.is_valid():
            current_topic = form.save(commit=False)
            current_topic.owner = request.user
            current_topic.save()
            form.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)
    # Check that the topic owner is the current user.
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            current_entry = form.save(commit=False)
            current_entry.topic = topic
            current_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'topic': topic,
               'form': form,
               }
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Check that the topic owner is the current user.
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # No data submitted; show existing entry
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; update the entry
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    # Display form with existing entry in html page
    context = {'entry': entry,
               'topic': topic,
               'form': form,
               }
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(request, topic):
    # Check the owner of a topic is the current logged-in user. If not raise an Http 404 error.
    if topic.owner != request.user:
        raise Http404

templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <title>Learning Logs App</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {%  bootstrap_javascript %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>

                <!-- Account-related links -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-2">Hello, {% if user.first_name %}{{ user.first_name }}
                                {% else %}{{ user.username }}{% endif %}</span>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{%  url 'accounts:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                    {%  endif %}

                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:logout' %}" method='post'>
                            {% csrf_token %}
                            <button name="submit" class="btn btn-outline-secondary btn-sm">
                                Log out</button>
                        </form>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>



</body>
</html>

templates/learning_logs/edit_entry.html
{%  extends 'learning_logs/base.html' %}
{%  load django_bootstrap5 %}

{% block page_header %}
    <h1>Topic: <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic.text }}</a></h1>
{% endblock page_header %}

{%  block content %}
    <p>Entry date: {{ entry.date_added|date:'M d, Y H:i' }}</p>
    <form action="{%  url 'learning_logs:edit_entry' entry.id %}" method="post">
        {%  csrf_token %}
        <div class="mb-3 form-floating">
            {{ form.text }}
            <label for="entryTextInput">Edit entry</label>
        </div>
        {% include "learning_logs/submit_cancel_buttons.html" with submit_name="Save changes" %}
    </form>

{% endblock content %}

templates/learning_logs/index.html
{%  extends 'learning_logs/base.html' %}

{%  block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track you learning</h1>

            <p class="lead">Make your own Learning Log, and keep a list of the topics you're
            learning about. Whenever you learn something new about a topic, make an entry summarising
            what you've learned.</p>
            <a class="btn btn-primary btn-lg mt-1"
               href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

templates/learning_logs/new_entry.html
{%  extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock %}

{%  block content %}
    <p>Add a new entry</p>
    <form action="{%  url 'learning_logs:new_entry' topic.id %}" method="post">
        {%  csrf_token %}
        {# renders each element in a separate div #}
        <div class="mb-3 form-floating">
            {{ form.text }}
            <label for="entryTextInput">Enter a new entry</label>
        </div>
        {% include "learning_logs/submit_cancel_buttons.html" with submit_name="Add entry" %}
    </form>

{% endblock content %}

templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h1>Add a new topic</h1>
{% endblock page_header %}

{%  block content %}
    <form action="{%  url 'learning_logs:new_topic' %}" method="post">
        {%  csrf_token %}

        {% bootstrap_form form %}

        {% include "learning_logs/submit_cancel_buttons.html" with submit_name="Add topic" %}

    </form>



{% endblock content %}

templates/learning_logs/submit_cancel_buttons.html
<button type="submit" class="btn btn-primary"> {{ submit_name }} </button>
<button onclick="window.history.back();" class="btn btn-secondary"
        type="button">Cancel</button>

templates/learning_logs/topic.html
{%  extends 'learning_logs/base.html' %}

{%  block page_header %}
    <h1>Topic: {{ topic.text }}</h1>
{% endblock page_header %}

{%  block content %}
    <p>
        <a href="{%  url 'learning_logs:new_entry' topic.id %}"> Add a new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <!-- Card header with timestamp and edit link -->
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
            </h4>
            <!-- Card body with entry text -->
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No topics have been added yet.</p>
    {% endfor %}
    <a class="btn btn-primary" href="{% url 'learning_logs:topics' %}">Topics</a>

{% endblock content %}

templates/learning_logs/topics.html
{%  extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul class="list-group border-bottom pb-2 mb-2">
      {%  for topic in topics %}
        <li class="list-group-item border-0">
            <a href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}</a></li>
      {% empty %}
        <li class="list-group-item border-0"> No topics have been added yet.</li>
      {% endfor %}
    </ul>
    <a class="btn btn-primary" href="{% url 'learning_logs:new_topic' %}">Add new topic</a>

{% endblock content %}